### ISSUE TITLE
This code is incompatible with C#

### ISSUE THREAD

**Issue by mburakeker** [HMS-Core/hms-iap-serverdemo#1]
Please fix the following lines, it's not compatible with C#.
Seems like they are written using Java:
https://github.com/HMS-Core/hms-iap-serverdemo/blob/bfa56456a6ca00efa6941b8ab3a1197211ddc230/Demo.cs#L202
https://github.com/HMS-Core/hms-iap-serverdemo/blob/bfa56456a6ca00efa6941b8ab3a1197211ddc230/Demo.cs#L432

**Comment by Mike-mei** [comment]
Thank you for reporting this issue, we have fixed the code in the latest update 0295a81
